course_registration/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :courses, only: [:show, :index, :new, :create] do
    resources :registrations, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :students do
      resources :grades
  end

  root to: 'application#home'

  end

course_registration/app/views/layouts/_navbar.html.erb
    <div class="topnav" id="myTopnav">

      <% if user_signed_in? %>

          <a class="nav-link" <%= link_to 'Log Out', destroy_user_session_path, method: :delete %></a>

          <a class="nav-link" <%= link_to "Home", root_path %></a>

          <a class="nav-link" <%= link_to "Courses", courses_path, class: 'all_courses' %></a>

          <a class="nav-link" <%= link_to "My Profile", user_path(current_user.id) %></a>

          <% else %>

          <a class="nav-link" <%= link_to "Sign In With Facebook", user_facebook_omniauth_authorize_path %></a>

          <a class="nav-link" <%= link_to 'Sign Up', new_user_registration_path %></a>

          <a class="nav-link" <%= link_to 'Log In', new_user_session_path %></a>

    <% end %>
</div>

course_registration/app/views/layouts/_school.html.erb
    <div class="school-banner">
        <div class="school-text" <%= link_to 'FLATIRON HIGH SCHOOL', root_path %></div>

<% if user_signed_in? %>

    <div class="school-logged-in">

  You are logged in as <%= current_user.email %>.
  <% else %>
  <% end %>
  </div>
</div>

course_registration/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course Registration</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">

  </head>

  <body>
<%= render 'layouts/school' %>
  <%= render 'layouts/navbar' %>

    <div class="flexbox-container">
	     <div><h3>Column 1</h3></div>
	      <div><h3><%= yield %></h3></div>
      </div>
</body>
</html>