course_registration/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :courses, only: [:show, :index, :new, :create] do
    resources :registrations, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :students do
      resources :grades
  end

  root to: 'application#home'

  end

course_registration/app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student
  belongs_to :user

  validates :behavior, presence: true
  validates :score, presence: true

  def self.smartest_students
    order('score desc').first(3)
  end

end

course_registration/app/controllers/grades_controller.rb
class GradesController < ApplicationController

  def index
    @student = Student.find_by_id(params[:student_id])
    @grades = @student.grades
  end

  def new
  @student = Student.find_by_id(params[:student_id])
  @grade = @student.grades.build
  end

  def create
    @grade = current_user.grades.build(grade_params)
      if @grade.save
    render json: @grade, status: 201
  else
      flash[:message] = @grade.errors.full_messages
    render json: {errors: @grade.errors.full_messages}, status: 400
  end
end

  def update
    @url = student_grade_path
    @grade = Grade.find(params[:id])
    if @grade.user_id = current_user.id
      @grade.update_attributes(grade_params)
      @grade.save
      redirect_to students_path
    else
      @grade.errors.add(:base, "You must be the original creator to make changes
      to this grade.")
      render :edit
    end
  end

  private

  def grade_params
    params.require(:grade).permit(:student_id, :user_id, :score, :behavior)
  end


end

course_registration/app/views/grades/_form.html.erb
<% if @grade.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@grade.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
    <% @grade.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </div>
<% end %><br>
<h3>
<%= form_for @grade, url: "/students/#{@student.id}/grades/#{@grade.id}" do |f| %>
  <% hidden_field_tag("student_id", "1", :id => @student.id) %>

  <%= f.label :behavior %>:
  <%= f.text_field :behavior %><br>

  <%= f.label :score %>:
  <%= f.number_field :score, min: 0, max: 100 %><br>

  <%= f.submit %>
  <% end %>
</h3>

course_registration/app/views/grades/edit.html.erb
<%= render 'form' %>

course_registration/app/views/grades/index.html.erb
<div>
  <h3>
    <%= @student.first_name %> <%= @student.last_name%></h3>
        <% @student.grades.each do |grade| %>
  <h4>
      Behavior: <%= grade.behavior %><br>
      Score: <%= grade.score %><br>
      <% if current_user.id == grade.user_id %>
        <%= link_to 'Update Grade', edit_student_grade_path(@student, grade) %><br>
        Submitted by: <%= grade.user.email %>
        <% else %>
        Submitted by: <%= grade.user.email %>
      <% end %>
<% end %>
<br><br>



<%= link_to "Add a Grade for #{@student.first_name}", new_student_grade_path(@student) %>
  </h4>
</div>
<h3><%= link_to "#{@student.first_name}'s Profile", student_path(@student) %></h3>
  <h3><%= link_to "Back to All Students", students_path %></h3>

course_registration/app/views/grades/new.html.erb
<%= render partial: "form", locals: {grade: @grade} %>
 <br>
 <div id="newGrade">
   <h2 id="gradeStudent"></h2>
   <p id="gradeBehavior"></p>
   <p id="gradeScore"></p>
 </div>
 <br>
 <p><%= link_to "Click here", student_grades_path(@grade.student) %> to view all of your current grades.</p>
</div>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $("form#new_grade").submit(function(e) {
      e.preventDefault();
      let values = $(this).serialize();
      let create_grade = $.post("/grades", values);
      create_grade.done(function(data) {
        let grade = data;
        $("#gradeStudent").text(grade.student);
        $("#gradeBehavior").text(grade.behavior);
        $("#gradeScore").text(grade.score});
      });
    });
  });
</script>