course_registration/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :courses, only: [:show, :index, :new, :create] do
    resources :registrations, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :students do
      resources :grades
  end

  root to: 'application#home'

  end

course_registration/app/models/student.rb
class Student < ActiveRecord::Base
  has_many :registrations
  has_many :courses, through: :registrations
  has_many :grades
  has_many :users, through: :grades


  validates :first_name, presence: true
  validates :last_name, presence: true

end

course_registration/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
      @students = Student.all
      @grades = current_user.grades.all
      respond_to do |f|
        f.html
        f.json {render json: @students}
      end
  end

  def show
    @student = Student.find_by_id(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = current_user.students.build(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find_by_id(params[:id])
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :course_id)
  end


end

course_registration/app/helpers/students_helper.rb
module StudentsHelper
end

course_registration/app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@student.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@student) do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>

  <%= f.label :course_id %>
  <%= f.collection_select :course_ids, Course.all, :id, :name %>

  <%= f.submit %>
  <% end %>

course_registration/app/views/students/index.html.erb
  <h3>All Flatiron High School Students</h3>
  <div class="student_info"><% @students.each do |student| %>
  <h4><%= student.first_name %> <%= student.last_name%></h4>
  <%= link_to "View #{student.first_name}'s Grades", student_grades_path(student) %><br>
  <%= link_to "Add New Grade for #{student.first_name}", new_student_grade_path(student) %><br>
<% end %></div><br>
<h4><%= link_to "Register a New Student", new_student_path %></h4>
  <h4><%= link_to "Enroll an Existing Student in a Course", courses_path %></h4>

course_registration/app/views/students/new.html.erb
<h3>Enroll a New Student</h3><br>
<%= render 'form' %>

course_registration/app/views/students/show.html.erb
<h2>Student Profile</h2>

  <h4><%= @student.first_name %> <%= @student.last_name %><br>
    ------------------------------<br>
<p>Enrolled in:</p></h4>
  <ol>
    <li><% @student.courses.each do |course|%>
    <%= course.section %> - <%= course.name%></li>
  </ol>
  </h4>
<% end %>
<h4>  <% if @student.grades.nil? %>
No grades available for <%= @student.first_name %> <%= @student.last_name %>.<br>
    <%= link_to "Add Grades for #{@student.first_name}", new_student_grade_path(@student) %>
  <% else %>
  <%= link_to "View #{@student.first_name}'s Grades", student_grades_path(@student) %><br>
  <%= link_to "Add #{@student.first_name} to a Course", courses_path %>
      <% end %></h4>
<br>
<h3>
<%= link_to "Back to All Students", students_path %><br>
<%= link_to "Back to All Courses", courses_path %></h3>

course_registration/app/views/students/smartest.html.erb
<h1>Top 3 Students</h1>
  <h2><% @grades = Grade.smartest_students %>
    <% @grades.each do |grade| %>
    <p><%= grade.student.first_name %> <%= grade.student.last_name %><br>
      <%= grade.score %> - <%= grade.behavior %></p>
  <% end %><br>
  <a href="#">Load More</a>
</h2>